name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js and cache npm dependencies
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm i

      # (Optional) Step: Lint your code (if you have a lint script)
      # - name: Lint code
      #   run: npm run lint

      # Step 4: Run tests
      - name: Run tests
        run: npm test -- --watchAll=false

      # Step 5: Build the React application (Fixed Indentation)
      - name: Build
        run: npm run build
